url: https://alpiepho.github.io
baseurl: /project-portfolio3/

# Site settings
title: Hi, I'm Al
email: alpiepho@yahoo.com
description: "Project Portfolio for Al Piepho written  with Jekyll.  Firmware, Software, Web."


# Team names, titles and social links
people:
- name: Al Piepho
  pic: 1
  position: Firmware | Software | Web
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/al-piepho-fw-sw-engineer/
    - title: github
      url: https://github.com/alpiepho

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/al-piepho-fw-sw-engineer/
  - title: twitter
    url: https://twitter.com/apiepho1
  - title: github
    url: https://github.com/alpiepho
  - title: envelope 
    url: mailto:alpiepho@gmail.com
  - title: book
    url: https://alpiepho.github.io/my-blog2

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-tactile