# Converting data from project-portfolio2...
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-vb-pwa.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-vb-pwa.png ../img/portfolio/screenshot-vb-pwa--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-gitprime-patterns.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-gitprime-patterns.png ../img/portfolio/screenshot-gitprime-patterns--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-terms-pwa-starter.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-terms-pwa-starter.png ../img/portfolio/screenshot-terms-pwa-starter--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-any-counter.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-any-counter.png ../img/portfolio/screenshot-any-counter--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-site-eval.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-site-eval.png ../img/portfolio/screenshot-site-eval--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-my-blog.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-my-blog.png ../img/portfolio/screenshot-my-blog--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-state-pwa.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-state-pwa.png ../img/portfolio/screenshot-state-pwa--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-state-static.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-state-static.png ../img/portfolio/screenshot-state-static--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-react-stats-bsb.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-react-stats-bsb.png ../img/portfolio/screenshot-react-stats-bsb--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/firmware-sc200.jpeg ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/firmware-sc200.jpeg ../img/portfolio/firmware-sc200--thumbnail.jpeg
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-rpn-hex-vscode.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-rpn-hex-vscode.png ../img/portfolio/screenshot-rpn-hex-vscode--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-rpn-hex-chrome.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-rpn-hex-chrome.png ../img/portfolio/screenshot-rpn-hex-chrome--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-purecss.png ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/screenshot-purecss.png ../img/portfolio/screenshot-purecss--thumbnail.png
cp ~/Projects/gatsby/project-portfolio2/static/images/firmware-broadcom-sas-sata-controller.jpg ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/firmware-broadcom-sas-sata-controller.jpg ../img/portfolio/firmware-broadcom-sas-sata-controller--thumbnail.jpg
cp ~/Projects/gatsby/project-portfolio2/static/images/firmware-pelco-sarix_1.jpg ../img/portfolio
cp ~/Projects/gatsby/project-portfolio2/static/images/firmware-pelco-sarix_1.jpg ../img/portfolio/firmware-pelco-sarix_1--thumbnail.jpg
# done.
